# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toilets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='toilet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='toilets.Toilets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toilets',
            name='lat',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='toilets',
            name='lon',
            field=models.CharField(max_length=30),
        ),
    ]
