# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0002_auto_20160319_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='toilets',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='toilets',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
