# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0003_auto_20160319_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toilets',
            old_name='visits',
            new_name='current_visits',
        ),
        migrations.AddField(
            model_name='toilets',
            name='total_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
